package net.satisfy.candlelight.core.registry;

import net.satisfy.foundation.flammable.FoundationFlammables;

import static net.satisfy.candlelight.core.registry.ObjectRegistry.*;

public class FlammableBlockRegistry {
    public static void init() {
        FoundationFlammables.plant(ROSE);
        FoundationFlammables.wool(NOTE_PAPER_BLOCK);
        FoundationFlammables.wood(BAMBOO_STOVE, BAMBOO_KITCHEN_SINK, BAMBOO_COUNTER, FLOORBOARD, CABINET, DRAWER, CHAIR, TABLE, SIDEBOARD, SIDE_TABLE, LAMP, SOFA, OAK_CABINET, OAK_DRAWER, OAK_CHAIR, OAK_TABLE, OAK_SHELF, OAK_BIG_TABLE, SPRUCE_CABINET, SPRUCE_DRAWER, SPRUCE_CHAIR, SPRUCE_TABLE, SPRUCE_SHELF, SPRUCE_BIG_TABLE, BIRCH_CABINET, BIRCH_DRAWER, BIRCH_CHAIR, BIRCH_TABLE, BIRCH_SHELF, BIRCH_BIG_TABLE, JUNGLE_CABINET, JUNGLE_DRAWER, JUNGLE_CHAIR, JUNGLE_TABLE, JUNGLE_SHELF, JUNGLE_BIG_TABLE, ACACIA_CABINET, ACACIA_DRAWER, ACACIA_CHAIR, ACACIA_TABLE, ACACIA_SHELF, ACACIA_BIG_TABLE, DARK_OAK_CABINET, DARK_OAK_DRAWER, DARK_OAK_CHAIR, DARK_OAK_TABLE, DARK_OAK_SHELF, DARK_OAK_BIG_TABLE, MANGROVE_CABINET, MANGROVE_DRAWER, MANGROVE_CHAIR, MANGROVE_TABLE, MANGROVE_SHELF, MANGROVE_BIG_TABLE, CHERRY_CABINET, CHERRY_DRAWER, CHERRY_CHAIR, CHERRY_TABLE, CHERRY_SHELF, CHERRY_BIG_TABLE, BAMBOO_CABINET, BAMBOO_DRAWER, BAMBOO_CHAIR, BAMBOO_TABLE, BAMBOO_SHELF, BAMBOO_BIG_TABLE);
    }
}
