package net.satisfy.candlelight.forge.config;

import net.neoforged.neoforge.common.ModConfigSpec;
import net.satisfy.candlelight.core.config.CandlelightConfig;

public final class CandlelightNeoForgeConfig {
    private static final ModConfigSpec.IntValue WELL_SERVED_FOOD_FLOOR;
    private static final ModConfigSpec.IntValue REFRESHED_MAX_CHARGES;
    private static final ModConfigSpec.BooleanValue RING_LUCK_ENABLED;
    private static final ModConfigSpec.IntValue RING_LUCK_AMPLIFIER;
    private static final ModConfigSpec.BooleanValue BANNER_GIVE_EFFECT;
    private static final ModConfigSpec.IntValue BANNER_RADIUS;
    private static final ModConfigSpec.IntValue BANNER_AMPLIFIER;
    private static final ModConfigSpec.DoubleValue TABLE_SET_FOOD_BONUS;
    private static final ModConfigSpec.DoubleValue ELEGANT_FOOD_BONUS;
    private static final ModConfigSpec.IntValue WELL_SERVED_TICKS_PER_COURSE;
    private static final ModConfigSpec.IntValue MAX_WELL_SERVED_TICKS;
    private static final ModConfigSpec.IntValue MENU_BONUS_TICKS;
    private static final ModConfigSpec.IntValue MAX_MENU_WELL_SERVED_TICKS;
    private static final ModConfigSpec.IntValue MENU_MAX_TICKS_BETWEEN_COURSES;
    private static final ModConfigSpec.BooleanValue DINNER_GUESTS;
    private static final ModConfigSpec.DoubleValue DINNER_GUEST_CHANCE;
    private static final ModConfigSpec.IntValue DINNER_GUEST_RANGE;
    private static final ModConfigSpec.IntValue DINNER_DISCOUNT_PERCENT;
    private static final ModConfigSpec.IntValue DINNER_DISCOUNT_TICKS;
    private static final ModConfigSpec.DoubleValue CHEF_SET_EXTRA_PORTION_CHANCE;
    private static final ModConfigSpec.BooleanValue TABLE_LIGHTS_ENABLED;
    private static final ModConfigSpec.IntValue TABLE_LIGHT_RADIUS;
    private static final ModConfigSpec.BooleanValue DINNER_MENU_ENABLED;
    private static final ModConfigSpec.BooleanValue TABLE_DRINKS_ENABLED;
    private static final ModConfigSpec.IntValue DINNER_START;
    private static final ModConfigSpec.IntValue DINNER_END;
    private static final ModConfigSpec.IntValue DINNER_GUEST_INTERVAL;
    private static final ModConfigSpec.BooleanValue NITWITS_EAT;
    private static final ModConfigSpec.BooleanValue DISCOUNT_ONLY_HOST;
    private static final ModConfigSpec.BooleanValue CHEF_SET_BONUS_ENABLED;
    private static final ModConfigSpec.BooleanValue ELEGANT_SET_BONUS_ENABLED;
    private static final ModConfigSpec.DoubleValue ZOMBIE_COOKING_HAT_CHANCE;
    private static final ModConfigSpec.BooleanValue NAPKIN_SOUND;
    private static final ModConfigSpec.BooleanValue DISH_STEAM;
    private static final ModConfigSpec.IntValue DISH_STEAM_TICKS;
    private static final ModConfigSpec.IntValue TABLE_SIGN_MAX_LINES;
    private static final ModConfigSpec.BooleanValue SHOW_TABLE_SET_INFO;
    private static final ModConfigSpec.BooleanValue SHOW_SET_BONUS_TOOLTIPS;
    private static final ModConfigSpec.IntValue TOMATO_SOUP_NUTRITION;
    private static final ModConfigSpec.DoubleValue TOMATO_SOUP_SATURATION;
    private static final ModConfigSpec.IntValue MUSHROOM_SOUP_NUTRITION;
    private static final ModConfigSpec.DoubleValue MUSHROOM_SOUP_SATURATION;
    private static final ModConfigSpec.IntValue PASTA_WITH_MOZZARELLA_NUTRITION;
    private static final ModConfigSpec.DoubleValue PASTA_WITH_MOZZARELLA_SATURATION;
    private static final ModConfigSpec.IntValue BOLOGNESE_NUTRITION;
    private static final ModConfigSpec.DoubleValue BOLOGNESE_SATURATION;
    private static final ModConfigSpec.IntValue BEEF_WITH_MUSHROOM_IN_WINE_AND_POTATOES_NUTRITION;
    private static final ModConfigSpec.DoubleValue BEEF_WITH_MUSHROOM_IN_WINE_AND_POTATOES_SATURATION;
    private static final ModConfigSpec.IntValue PASTA_WITH_BOLOGNESE_NUTRITION;
    private static final ModConfigSpec.DoubleValue PASTA_WITH_BOLOGNESE_SATURATION;
    private static final ModConfigSpec.IntValue ROASTBEEF_WITH_GLAZED_CARROTS_NUTRITION;
    private static final ModConfigSpec.DoubleValue ROASTBEEF_WITH_GLAZED_CARROTS_SATURATION;
    private static final ModConfigSpec.IntValue ROASTED_LAMB_WITH_LETTUCE_NUTRITION;
    private static final ModConfigSpec.DoubleValue ROASTED_LAMB_WITH_LETTUCE_SATURATION;
    private static final ModConfigSpec.IntValue FILLET_STEAK_NUTRITION;
    private static final ModConfigSpec.DoubleValue FILLET_STEAK_SATURATION;
    private static final ModConfigSpec.IntValue TROPICAL_FISH_SUPREME_NUTRITION;
    private static final ModConfigSpec.DoubleValue TROPICAL_FISH_SUPREME_SATURATION;
    private static final ModConfigSpec.IntValue CHICKEN_ALFREDO_NUTRITION;
    private static final ModConfigSpec.DoubleValue CHICKEN_ALFREDO_SATURATION;
    private static final ModConfigSpec.IntValue SALMON_ON_WHITE_WINE_NUTRITION;
    private static final ModConfigSpec.DoubleValue SALMON_ON_WHITE_WINE_SATURATION;
    private static final ModConfigSpec.IntValue CHICKEN_WITH_VEGETABLES_NUTRITION;
    private static final ModConfigSpec.DoubleValue CHICKEN_WITH_VEGETABLES_SATURATION;
    private static final ModConfigSpec.IntValue PORK_RIBS_NUTRITION;
    private static final ModConfigSpec.DoubleValue PORK_RIBS_SATURATION;
    private static final ModConfigSpec.IntValue LASAGNE_NUTRITION;
    private static final ModConfigSpec.DoubleValue LASAGNE_SATURATION;
    private static final ModConfigSpec.IntValue BEEF_WELLINGTON_NUTRITION;
    private static final ModConfigSpec.DoubleValue BEEF_WELLINGTON_SATURATION;
    private static final ModConfigSpec.IntValue MOZZARELLA_NUTRITION;
    private static final ModConfigSpec.DoubleValue MOZZARELLA_SATURATION;
    private static final ModConfigSpec.IntValue POTROAST_NUTRITION;
    private static final ModConfigSpec.DoubleValue POTROAST_SATURATION;
    private static final ModConfigSpec.IntValue BEETROOT_SALAD_NUTRITION;
    private static final ModConfigSpec.DoubleValue BEETROOT_SALAD_SATURATION;
    private static final ModConfigSpec.IntValue BEETROOT_SALAD_EFFECT_DURATION;
    private static final ModConfigSpec.IntValue CHICKEN_TERIYAKI_NUTRITION;
    private static final ModConfigSpec.DoubleValue CHICKEN_TERIYAKI_SATURATION;
    private static final ModConfigSpec.IntValue CHICKEN_TERIYAKI_EFFECT_DURATION;
    private static final ModConfigSpec.IntValue SALAD_NUTRITION;
    private static final ModConfigSpec.DoubleValue SALAD_SATURATION;
    private static final ModConfigSpec.IntValue SALAD_EFFECT_DURATION;
    private static final ModConfigSpec.IntValue BEEF_TARTARE_NUTRITION;
    private static final ModConfigSpec.DoubleValue BEEF_TARTARE_SATURATION;
    private static final ModConfigSpec.IntValue BEEF_TARTARE_EFFECT_DURATION;
    private static final ModConfigSpec.IntValue PASTA_WITH_LETTUCE_NUTRITION;
    private static final ModConfigSpec.DoubleValue PASTA_WITH_LETTUCE_SATURATION;
    private static final ModConfigSpec.IntValue PASTA_WITH_LETTUCE_EFFECT_DURATION;
    private static final ModConfigSpec.IntValue OMELET_NUTRITION;
    private static final ModConfigSpec.DoubleValue OMELET_SATURATION;
    private static final ModConfigSpec.IntValue OMELET_EFFECT_DURATION;
    private static final ModConfigSpec.IntValue HARVEST_PLATE_NUTRITION;
    private static final ModConfigSpec.DoubleValue HARVEST_PLATE_SATURATION;
    private static final ModConfigSpec.IntValue HARVEST_PLATE_EFFECT_DURATION;
    private static final ModConfigSpec.IntValue CHOCOLATE_MOUSSE_NUTRITION;
    private static final ModConfigSpec.DoubleValue CHOCOLATE_MOUSSE_SATURATION;
    private static final ModConfigSpec.IntValue CHOCOLATE_MOUSSE_EFFECT_DURATION;
    private static final ModConfigSpec.IntValue FRESH_GARDEN_SALAD_NUTRITION;
    private static final ModConfigSpec.DoubleValue FRESH_GARDEN_SALAD_SATURATION;
    private static final ModConfigSpec.IntValue FRESH_GARDEN_SALAD_EFFECT_DURATION;
    private static final ModConfigSpec.IntValue TOMATO_MOZZARELLA_SALAD_NUTRITION;
    private static final ModConfigSpec.DoubleValue TOMATO_MOZZARELLA_SALAD_SATURATION;
    private static final ModConfigSpec.IntValue TOMATO_MOZZARELLA_SALAD_EFFECT_DURATION;
    public static final ModConfigSpec COMMON;

    static {
        ModConfigSpec.Builder common = new ModConfigSpec.Builder();
        common.push("effects");
        WELL_SERVED_FOOD_FLOOR = common.comment("Your hunger never drops below this while Well Served is active").defineInRange("wellServedFoodFloor", 8, 0, 20);
        REFRESHED_MAX_CHARGES = common.comment("How many harvests Refreshed covers").defineInRange("refreshedMaxCharges", 10, 1, 64);
        RING_LUCK_ENABLED = common.comment("Wearing the Gold Ring gives Luck").define("ringLuckEnabled", true);
        RING_LUCK_AMPLIFIER = common.comment("0 is Luck I, 1 is Luck II").defineInRange("ringLuckAmplifier", 1, 0, 4);
        BANNER_GIVE_EFFECT = common.comment("Players near a placed Completionist Banner get its effect").define("bannerGiveEffect", true);
        BANNER_RADIUS = common.comment("Radius of the Completionist Banner effect").defineInRange("bannerRadius", 8, 1, 32);
        BANNER_AMPLIFIER = common.comment("Level of the Completionist Banner effect, 0 is level I").defineInRange("bannerAmplifier", 0, 0, 4);
        common.pop();
        common.push("misc");
        TABLE_SET_FOOD_BONUS = common.comment("Food eaten from a Table Set fills you up this many times more").defineInRange("tableSetFoodBonus", 1.3, 1.0, 3.0);
        ELEGANT_FOOD_BONUS = common.comment("Food bonus with a full Suit or Evening Dress").defineInRange("elegantFoodBonus", 1.5, 1.0, 3.0);
        WELL_SERVED_TICKS_PER_COURSE = common.comment("Extra Well Served for every table setting, 1200 ticks are one minute").defineInRange("wellServedTicksPerCourse", 1200, 0, 12000);
        MAX_WELL_SERVED_TICKS = common.comment("Longest Well Served you can get from a Table Set").defineInRange("maxWellServedTicks", 12000, 0, 72000);
        MENU_BONUS_TICKS = common.comment("Extra Well Served and Refreshed for a full menu").defineInRange("menuBonusTicks", 6000, 0, 72000);
        MAX_MENU_WELL_SERVED_TICKS = common.comment("Longest Well Served you can get from a full menu").defineInRange("maxMenuWellServedTicks", 18000, 0, 72000);
        MENU_MAX_TICKS_BETWEEN_COURSES = common.comment("How long you may wait between two courses").defineInRange("menuMaxTicksBetweenCourses", 6000, 200, 72000);
        DINNER_GUESTS = common.comment("Villagers may eat dishes from Table Sets in the evening").define("dinnerGuests", true);
        DINNER_GUEST_CHANCE = common.comment("Chance every 10 seconds that a villager comes to the table").defineInRange("dinnerGuestChance", 0.3, 0.0, 1.0);
        DINNER_GUEST_RANGE = common.comment("How far away villagers notice the dish").defineInRange("dinnerGuestRange", 16, 4, 64);
        DINNER_DISCOUNT_PERCENT = common.comment("Discount on all trades after the dinner").defineInRange("dinnerDiscountPercent", 10, 0, 100);
        DINNER_DISCOUNT_TICKS = common.comment("24000 ticks are one Minecraft day").defineInRange("dinnerDiscountTicks", 24000, 1200, 240000);
        CHEF_SET_EXTRA_PORTION_CHANCE = common.comment("Chance of an extra portion from Cooking Pan and Cooking Pot with the full set").defineInRange("chefSetExtraPortionChance", 0.25, 0.0, 1.0);
        TABLE_LIGHTS_ENABLED = common.comment("A lit candle or lamp next to a Table Set counts as a table setting").define("tableLightsEnabled", true);
        TABLE_LIGHT_RADIUS = common.comment("How far away a light may stand from the Table Set").defineInRange("tableLightRadius", 1, 1, 4);
        DINNER_MENU_ENABLED = common.comment("Starter, main course and dessert in a row give a bonus").define("dinnerMenuEnabled", true);
        TABLE_DRINKS_ENABLED = common.comment("Drinks can be poured into the glasses of a Table Set").define("tableDrinksEnabled", true);
        DINNER_START = common.comment("Time of day from which villagers come to dinner, 9000 is after work").defineInRange("dinnerStart", 9000, 0, 24000);
        DINNER_END = common.comment("Time of day until villagers come to dinner, 12000 is bedtime").defineInRange("dinnerEnd", 12000, 0, 24000);
        DINNER_GUEST_INTERVAL = common.comment("How often a Table Set looks for a guest, 200 ticks are 10 seconds").defineInRange("dinnerGuestInterval", 200, 20, 6000);
        NITWITS_EAT = common.comment("Nitwits eat the dish but give no discount").define("nitwitsEat", true);
        DISCOUNT_ONLY_HOST = common.comment("Only the player who served the dish gets the discount").define("discountOnlyHost", false);
        CHEF_SET_BONUS_ENABLED = common.comment("Turn the Chef's Outfit set bonus on or off").define("chefSetBonusEnabled", true);
        ELEGANT_SET_BONUS_ENABLED = common.comment("Turn the Suit and Evening Dress set bonus on or off").define("elegantSetBonusEnabled", true);
        ZOMBIE_COOKING_HAT_CHANCE = common.comment("Chance that a zombie spawns with a Cooking Hat").defineInRange("zombieCookingHatChance", 0.03, 0.0, 1.0);
        NAPKIN_SOUND = common.comment("Play a soft sound while dabbing with a Napkin").define("napkinSound", true);
        DISH_STEAM = common.comment("Freshly served dishes on a Table Set steam for a while").define("dishSteam", true);
        DISH_STEAM_TICKS = common.comment("How long freshly served dishes steam, in ticks").defineInRange("dishSteamTicks", 2400, 200, 12000);
        TABLE_SIGN_MAX_LINES = common.comment("How many lines fit on a Table Sign").defineInRange("tableSignMaxLines", 8, 1, 12);
        SHOW_TABLE_SET_INFO = common.comment("Show the info tooltip when looking at a Table Set").define("showTableSetInfo", true);
        SHOW_SET_BONUS_TOOLTIPS = common.comment("Show the set pieces and bonus on clothing").define("showSetBonusTooltips", true);
        common.pop();
        common.comment("Food values. Restart the game after changing them.").push("food");
        TOMATO_SOUP_NUTRITION = common.defineInRange("tomatoSoupNutrition", 6, 1, 20);
        TOMATO_SOUP_SATURATION = common.defineInRange("tomatoSoupSaturation", 0.6, 0.0, 2.0);
        MUSHROOM_SOUP_NUTRITION = common.defineInRange("mushroomSoupNutrition", 4, 1, 20);
        MUSHROOM_SOUP_SATURATION = common.defineInRange("mushroomSoupSaturation", 0.5, 0.0, 2.0);
        PASTA_WITH_MOZZARELLA_NUTRITION = common.defineInRange("pastaWithMozzarellaNutrition", 10, 1, 20);
        PASTA_WITH_MOZZARELLA_SATURATION = common.defineInRange("pastaWithMozzarellaSaturation", 0.7, 0.0, 2.0);
        BOLOGNESE_NUTRITION = common.defineInRange("bologneseNutrition", 10, 1, 20);
        BOLOGNESE_SATURATION = common.defineInRange("bologneseSaturation", 0.7, 0.0, 2.0);
        BEEF_WITH_MUSHROOM_IN_WINE_AND_POTATOES_NUTRITION = common.defineInRange("beefWithMushroomInWineAndPotatoesNutrition", 10, 1, 20);
        BEEF_WITH_MUSHROOM_IN_WINE_AND_POTATOES_SATURATION = common.defineInRange("beefWithMushroomInWineAndPotatoesSaturation", 0.7, 0.0, 2.0);
        PASTA_WITH_BOLOGNESE_NUTRITION = common.defineInRange("pastaWithBologneseNutrition", 12, 1, 20);
        PASTA_WITH_BOLOGNESE_SATURATION = common.defineInRange("pastaWithBologneseSaturation", 0.8, 0.0, 2.0);
        ROASTBEEF_WITH_GLAZED_CARROTS_NUTRITION = common.defineInRange("roastbeefWithGlazedCarrotsNutrition", 8, 1, 20);
        ROASTBEEF_WITH_GLAZED_CARROTS_SATURATION = common.defineInRange("roastbeefWithGlazedCarrotsSaturation", 0.8, 0.0, 2.0);
        ROASTED_LAMB_WITH_LETTUCE_NUTRITION = common.defineInRange("roastedLambWithLettuceNutrition", 8, 1, 20);
        ROASTED_LAMB_WITH_LETTUCE_SATURATION = common.defineInRange("roastedLambWithLettuceSaturation", 0.8, 0.0, 2.0);
        FILLET_STEAK_NUTRITION = common.defineInRange("filletSteakNutrition", 8, 1, 20);
        FILLET_STEAK_SATURATION = common.defineInRange("filletSteakSaturation", 0.8, 0.0, 2.0);
        TROPICAL_FISH_SUPREME_NUTRITION = common.defineInRange("tropicalFishSupremeNutrition", 6, 1, 20);
        TROPICAL_FISH_SUPREME_SATURATION = common.defineInRange("tropicalFishSupremeSaturation", 1.2, 0.0, 2.0);
        CHICKEN_ALFREDO_NUTRITION = common.defineInRange("chickenAlfredoNutrition", 10, 1, 20);
        CHICKEN_ALFREDO_SATURATION = common.defineInRange("chickenAlfredoSaturation", 0.8, 0.0, 2.0);
        SALMON_ON_WHITE_WINE_NUTRITION = common.defineInRange("salmonOnWhiteWineNutrition", 5, 1, 20);
        SALMON_ON_WHITE_WINE_SATURATION = common.defineInRange("salmonOnWhiteWineSaturation", 0.8, 0.0, 2.0);
        CHICKEN_WITH_VEGETABLES_NUTRITION = common.defineInRange("chickenWithVegetablesNutrition", 6, 1, 20);
        CHICKEN_WITH_VEGETABLES_SATURATION = common.defineInRange("chickenWithVegetablesSaturation", 1.2, 0.0, 2.0);
        PORK_RIBS_NUTRITION = common.defineInRange("porkRibsNutrition", 7, 1, 20);
        PORK_RIBS_SATURATION = common.defineInRange("porkRibsSaturation", 0.8, 0.0, 2.0);
        LASAGNE_NUTRITION = common.defineInRange("lasagneNutrition", 10, 1, 20);
        LASAGNE_SATURATION = common.defineInRange("lasagneSaturation", 0.7, 0.0, 2.0);
        BEEF_WELLINGTON_NUTRITION = common.defineInRange("beefWellingtonNutrition", 10, 1, 20);
        BEEF_WELLINGTON_SATURATION = common.defineInRange("beefWellingtonSaturation", 0.7, 0.0, 2.0);
        MOZZARELLA_NUTRITION = common.defineInRange("mozzarellaNutrition", 5, 1, 20);
        MOZZARELLA_SATURATION = common.defineInRange("mozzarellaSaturation", 0.6, 0.0, 2.0);
        POTROAST_NUTRITION = common.defineInRange("potroastNutrition", 12, 1, 20);
        POTROAST_SATURATION = common.defineInRange("potroastSaturation", 0.9, 0.0, 2.0);
        BEETROOT_SALAD_NUTRITION = common.defineInRange("beetrootSaladNutrition", 5, 1, 20);
        BEETROOT_SALAD_SATURATION = common.defineInRange("beetrootSaladSaturation", 0.6, 0.0, 2.0);
        BEETROOT_SALAD_EFFECT_DURATION = common.defineInRange("beetrootSaladEffectDuration", 2400, 0, 72000);
        CHICKEN_TERIYAKI_NUTRITION = common.defineInRange("chickenTeriyakiNutrition", 8, 1, 20);
        CHICKEN_TERIYAKI_SATURATION = common.defineInRange("chickenTeriyakiSaturation", 0.8, 0.0, 2.0);
        CHICKEN_TERIYAKI_EFFECT_DURATION = common.defineInRange("chickenTeriyakiEffectDuration", 6000, 0, 72000);
        SALAD_NUTRITION = common.defineInRange("saladNutrition", 5, 1, 20);
        SALAD_SATURATION = common.defineInRange("saladSaturation", 0.7, 0.0, 2.0);
        SALAD_EFFECT_DURATION = common.defineInRange("saladEffectDuration", 3600, 0, 72000);
        BEEF_TARTARE_NUTRITION = common.defineInRange("beefTartareNutrition", 8, 1, 20);
        BEEF_TARTARE_SATURATION = common.defineInRange("beefTartareSaturation", 0.9, 0.0, 2.0);
        BEEF_TARTARE_EFFECT_DURATION = common.defineInRange("beefTartareEffectDuration", 3000, 0, 72000);
        PASTA_WITH_LETTUCE_NUTRITION = common.defineInRange("pastaWithLettuceNutrition", 8, 1, 20);
        PASTA_WITH_LETTUCE_SATURATION = common.defineInRange("pastaWithLettuceSaturation", 0.9, 0.0, 2.0);
        PASTA_WITH_LETTUCE_EFFECT_DURATION = common.defineInRange("pastaWithLettuceEffectDuration", 3600, 0, 72000);
        OMELET_NUTRITION = common.defineInRange("omeletNutrition", 8, 1, 20);
        OMELET_SATURATION = common.defineInRange("omeletSaturation", 0.4, 0.0, 2.0);
        OMELET_EFFECT_DURATION = common.defineInRange("omeletEffectDuration", 4800, 0, 72000);
        HARVEST_PLATE_NUTRITION = common.defineInRange("harvestPlateNutrition", 7, 1, 20);
        HARVEST_PLATE_SATURATION = common.defineInRange("harvestPlateSaturation", 0.8, 0.0, 2.0);
        HARVEST_PLATE_EFFECT_DURATION = common.defineInRange("harvestPlateEffectDuration", 4800, 0, 72000);
        CHOCOLATE_MOUSSE_NUTRITION = common.defineInRange("chocolateMousseNutrition", 4, 1, 20);
        CHOCOLATE_MOUSSE_SATURATION = common.defineInRange("chocolateMousseSaturation", 0.3, 0.0, 2.0);
        CHOCOLATE_MOUSSE_EFFECT_DURATION = common.defineInRange("chocolateMousseEffectDuration", 2400, 0, 72000);
        FRESH_GARDEN_SALAD_NUTRITION = common.defineInRange("freshGardenSaladNutrition", 6, 1, 20);
        FRESH_GARDEN_SALAD_SATURATION = common.defineInRange("freshGardenSaladSaturation", 0.9, 0.0, 2.0);
        FRESH_GARDEN_SALAD_EFFECT_DURATION = common.defineInRange("freshGardenSaladEffectDuration", 3600, 0, 72000);
        TOMATO_MOZZARELLA_SALAD_NUTRITION = common.defineInRange("tomatoMozzarellaSaladNutrition", 5, 1, 20);
        TOMATO_MOZZARELLA_SALAD_SATURATION = common.defineInRange("tomatoMozzarellaSaladSaturation", 0.7, 0.0, 2.0);
        TOMATO_MOZZARELLA_SALAD_EFFECT_DURATION = common.defineInRange("tomatoMozzarellaSaladEffectDuration", 4800, 0, 72000);
        common.pop();
        COMMON = common.build();
    }

    private CandlelightNeoForgeConfig() {
    }

    public static void applyCommon() {
        CandlelightConfig.wellServedFoodFloor = WELL_SERVED_FOOD_FLOOR.get();
        CandlelightConfig.refreshedMaxCharges = REFRESHED_MAX_CHARGES.get();
        CandlelightConfig.ringLuckEnabled = RING_LUCK_ENABLED.get();
        CandlelightConfig.ringLuckAmplifier = RING_LUCK_AMPLIFIER.get();
        CandlelightConfig.bannerGiveEffect = BANNER_GIVE_EFFECT.get();
        CandlelightConfig.bannerRadius = BANNER_RADIUS.get();
        CandlelightConfig.bannerAmplifier = BANNER_AMPLIFIER.get();
        CandlelightConfig.tableSetFoodBonus = TABLE_SET_FOOD_BONUS.get();
        CandlelightConfig.elegantFoodBonus = ELEGANT_FOOD_BONUS.get();
        CandlelightConfig.wellServedTicksPerCourse = WELL_SERVED_TICKS_PER_COURSE.get();
        CandlelightConfig.maxWellServedTicks = MAX_WELL_SERVED_TICKS.get();
        CandlelightConfig.menuBonusTicks = MENU_BONUS_TICKS.get();
        CandlelightConfig.maxMenuWellServedTicks = MAX_MENU_WELL_SERVED_TICKS.get();
        CandlelightConfig.menuMaxTicksBetweenCourses = MENU_MAX_TICKS_BETWEEN_COURSES.get();
        CandlelightConfig.dinnerGuests = DINNER_GUESTS.get();
        CandlelightConfig.dinnerGuestChance = DINNER_GUEST_CHANCE.get();
        CandlelightConfig.dinnerGuestRange = DINNER_GUEST_RANGE.get();
        CandlelightConfig.dinnerDiscountPercent = DINNER_DISCOUNT_PERCENT.get();
        CandlelightConfig.dinnerDiscountTicks = DINNER_DISCOUNT_TICKS.get();
        CandlelightConfig.chefSetExtraPortionChance = CHEF_SET_EXTRA_PORTION_CHANCE.get();
        CandlelightConfig.tableLightsEnabled = TABLE_LIGHTS_ENABLED.get();
        CandlelightConfig.tableLightRadius = TABLE_LIGHT_RADIUS.get();
        CandlelightConfig.dinnerMenuEnabled = DINNER_MENU_ENABLED.get();
        CandlelightConfig.tableDrinksEnabled = TABLE_DRINKS_ENABLED.get();
        CandlelightConfig.dinnerStart = DINNER_START.get();
        CandlelightConfig.dinnerEnd = DINNER_END.get();
        CandlelightConfig.dinnerGuestInterval = DINNER_GUEST_INTERVAL.get();
        CandlelightConfig.nitwitsEat = NITWITS_EAT.get();
        CandlelightConfig.discountOnlyHost = DISCOUNT_ONLY_HOST.get();
        CandlelightConfig.chefSetBonusEnabled = CHEF_SET_BONUS_ENABLED.get();
        CandlelightConfig.elegantSetBonusEnabled = ELEGANT_SET_BONUS_ENABLED.get();
        CandlelightConfig.zombieCookingHatChance = ZOMBIE_COOKING_HAT_CHANCE.get();
        CandlelightConfig.napkinSound = NAPKIN_SOUND.get();
        CandlelightConfig.dishSteam = DISH_STEAM.get();
        CandlelightConfig.dishSteamTicks = DISH_STEAM_TICKS.get();
        CandlelightConfig.tableSignMaxLines = TABLE_SIGN_MAX_LINES.get();
        CandlelightConfig.showTableSetInfo = SHOW_TABLE_SET_INFO.get();
        CandlelightConfig.showSetBonusTooltips = SHOW_SET_BONUS_TOOLTIPS.get();
        CandlelightConfig.tomatoSoupNutrition = TOMATO_SOUP_NUTRITION.get();
        CandlelightConfig.tomatoSoupSaturation = TOMATO_SOUP_SATURATION.get();
        CandlelightConfig.mushroomSoupNutrition = MUSHROOM_SOUP_NUTRITION.get();
        CandlelightConfig.mushroomSoupSaturation = MUSHROOM_SOUP_SATURATION.get();
        CandlelightConfig.pastaWithMozzarellaNutrition = PASTA_WITH_MOZZARELLA_NUTRITION.get();
        CandlelightConfig.pastaWithMozzarellaSaturation = PASTA_WITH_MOZZARELLA_SATURATION.get();
        CandlelightConfig.bologneseNutrition = BOLOGNESE_NUTRITION.get();
        CandlelightConfig.bologneseSaturation = BOLOGNESE_SATURATION.get();
        CandlelightConfig.beefWithMushroomInWineAndPotatoesNutrition = BEEF_WITH_MUSHROOM_IN_WINE_AND_POTATOES_NUTRITION.get();
        CandlelightConfig.beefWithMushroomInWineAndPotatoesSaturation = BEEF_WITH_MUSHROOM_IN_WINE_AND_POTATOES_SATURATION.get();
        CandlelightConfig.pastaWithBologneseNutrition = PASTA_WITH_BOLOGNESE_NUTRITION.get();
        CandlelightConfig.pastaWithBologneseSaturation = PASTA_WITH_BOLOGNESE_SATURATION.get();
        CandlelightConfig.roastbeefWithGlazedCarrotsNutrition = ROASTBEEF_WITH_GLAZED_CARROTS_NUTRITION.get();
        CandlelightConfig.roastbeefWithGlazedCarrotsSaturation = ROASTBEEF_WITH_GLAZED_CARROTS_SATURATION.get();
        CandlelightConfig.roastedLambWithLettuceNutrition = ROASTED_LAMB_WITH_LETTUCE_NUTRITION.get();
        CandlelightConfig.roastedLambWithLettuceSaturation = ROASTED_LAMB_WITH_LETTUCE_SATURATION.get();
        CandlelightConfig.filletSteakNutrition = FILLET_STEAK_NUTRITION.get();
        CandlelightConfig.filletSteakSaturation = FILLET_STEAK_SATURATION.get();
        CandlelightConfig.tropicalFishSupremeNutrition = TROPICAL_FISH_SUPREME_NUTRITION.get();
        CandlelightConfig.tropicalFishSupremeSaturation = TROPICAL_FISH_SUPREME_SATURATION.get();
        CandlelightConfig.chickenAlfredoNutrition = CHICKEN_ALFREDO_NUTRITION.get();
        CandlelightConfig.chickenAlfredoSaturation = CHICKEN_ALFREDO_SATURATION.get();
        CandlelightConfig.salmonOnWhiteWineNutrition = SALMON_ON_WHITE_WINE_NUTRITION.get();
        CandlelightConfig.salmonOnWhiteWineSaturation = SALMON_ON_WHITE_WINE_SATURATION.get();
        CandlelightConfig.chickenWithVegetablesNutrition = CHICKEN_WITH_VEGETABLES_NUTRITION.get();
        CandlelightConfig.chickenWithVegetablesSaturation = CHICKEN_WITH_VEGETABLES_SATURATION.get();
        CandlelightConfig.porkRibsNutrition = PORK_RIBS_NUTRITION.get();
        CandlelightConfig.porkRibsSaturation = PORK_RIBS_SATURATION.get();
        CandlelightConfig.lasagneNutrition = LASAGNE_NUTRITION.get();
        CandlelightConfig.lasagneSaturation = LASAGNE_SATURATION.get();
        CandlelightConfig.beefWellingtonNutrition = BEEF_WELLINGTON_NUTRITION.get();
        CandlelightConfig.beefWellingtonSaturation = BEEF_WELLINGTON_SATURATION.get();
        CandlelightConfig.mozzarellaNutrition = MOZZARELLA_NUTRITION.get();
        CandlelightConfig.mozzarellaSaturation = MOZZARELLA_SATURATION.get();
        CandlelightConfig.potroastNutrition = POTROAST_NUTRITION.get();
        CandlelightConfig.potroastSaturation = POTROAST_SATURATION.get();
        CandlelightConfig.beetrootSaladNutrition = BEETROOT_SALAD_NUTRITION.get();
        CandlelightConfig.beetrootSaladSaturation = BEETROOT_SALAD_SATURATION.get();
        CandlelightConfig.beetrootSaladEffectDuration = BEETROOT_SALAD_EFFECT_DURATION.get();
        CandlelightConfig.chickenTeriyakiNutrition = CHICKEN_TERIYAKI_NUTRITION.get();
        CandlelightConfig.chickenTeriyakiSaturation = CHICKEN_TERIYAKI_SATURATION.get();
        CandlelightConfig.chickenTeriyakiEffectDuration = CHICKEN_TERIYAKI_EFFECT_DURATION.get();
        CandlelightConfig.saladNutrition = SALAD_NUTRITION.get();
        CandlelightConfig.saladSaturation = SALAD_SATURATION.get();
        CandlelightConfig.saladEffectDuration = SALAD_EFFECT_DURATION.get();
        CandlelightConfig.beefTartareNutrition = BEEF_TARTARE_NUTRITION.get();
        CandlelightConfig.beefTartareSaturation = BEEF_TARTARE_SATURATION.get();
        CandlelightConfig.beefTartareEffectDuration = BEEF_TARTARE_EFFECT_DURATION.get();
        CandlelightConfig.pastaWithLettuceNutrition = PASTA_WITH_LETTUCE_NUTRITION.get();
        CandlelightConfig.pastaWithLettuceSaturation = PASTA_WITH_LETTUCE_SATURATION.get();
        CandlelightConfig.pastaWithLettuceEffectDuration = PASTA_WITH_LETTUCE_EFFECT_DURATION.get();
        CandlelightConfig.omeletNutrition = OMELET_NUTRITION.get();
        CandlelightConfig.omeletSaturation = OMELET_SATURATION.get();
        CandlelightConfig.omeletEffectDuration = OMELET_EFFECT_DURATION.get();
        CandlelightConfig.harvestPlateNutrition = HARVEST_PLATE_NUTRITION.get();
        CandlelightConfig.harvestPlateSaturation = HARVEST_PLATE_SATURATION.get();
        CandlelightConfig.harvestPlateEffectDuration = HARVEST_PLATE_EFFECT_DURATION.get();
        CandlelightConfig.chocolateMousseNutrition = CHOCOLATE_MOUSSE_NUTRITION.get();
        CandlelightConfig.chocolateMousseSaturation = CHOCOLATE_MOUSSE_SATURATION.get();
        CandlelightConfig.chocolateMousseEffectDuration = CHOCOLATE_MOUSSE_EFFECT_DURATION.get();
        CandlelightConfig.freshGardenSaladNutrition = FRESH_GARDEN_SALAD_NUTRITION.get();
        CandlelightConfig.freshGardenSaladSaturation = FRESH_GARDEN_SALAD_SATURATION.get();
        CandlelightConfig.freshGardenSaladEffectDuration = FRESH_GARDEN_SALAD_EFFECT_DURATION.get();
        CandlelightConfig.tomatoMozzarellaSaladNutrition = TOMATO_MOZZARELLA_SALAD_NUTRITION.get();
        CandlelightConfig.tomatoMozzarellaSaladSaturation = TOMATO_MOZZARELLA_SALAD_SATURATION.get();
        CandlelightConfig.tomatoMozzarellaSaladEffectDuration = TOMATO_MOZZARELLA_SALAD_EFFECT_DURATION.get();
    }
}
